name: Deploy to Render

on:
  push:
    branches:
      - main  # or your deploy branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Render using Render Deploy Hook
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
